import localFont from "next/font/local";
import "./globals.css";
import { Outfit } from 'next/font/google';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Import the Outfit font and set it to use the Latin subset
const outfit = Outfit({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      className={outfit.className}>
        {children}
      </body>
    </html>
  );
}
